import {
  Home,
  Compass,
  Plus,
  MessageCircle,
  User,
  Bell,
  Search,
  Link2,
  Image,
  StickyNote,
  List,
  MapPin,
  Calendar,
  Mountain,
  ArrowRight,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  Heart,
  MoreHorizontal,
  X,
  Check,
  Lock,
  Clock,
  Route,
  Ruler,
  TrendingUp,
  Users,
  Share2,
  Settings,
  Shield,
  Star,
  Send,
  SlidersHorizontal,
  Globe,
  Camera,
  Trophy,
  Flag,
  Upload,
  Pencil,
  Download,
  LayoutGrid,
  Trash2,
  Layers,
  ThumbsUp,
  Sun,
  Moon,
  MountainSnow,
  Maximize2,
  type LucideIcon,
} from 'lucide-react';

/** Mapa de nombres del diseño (yv-kit) → iconos de lucide, mismo grosor (1.6). */
const MAP: Record<string, LucideIcon> = {
  home: Home,
  compass: Compass,
  plus: Plus,
  chat: MessageCircle,
  user: User,
  bell: Bell,
  search: Search,
  link: Link2,
  image: Image,
  note: StickyNote,
  list: List,
  pin: MapPin,
  calendar: Calendar,
  mountain: Mountain,
  arrow: ArrowRight,
  chevron: ChevronRight,
  chevdown: ChevronDown,
  back: ChevronLeft,
  heart: Heart,
  more: MoreHorizontal,
  x: X,
  check: Check,
  lock: Lock,
  clock: Clock,
  route: Route,
  ruler: Ruler,
  elev: TrendingUp,
  users: Users,
  share: Share2,
  settings: Settings,
  shield: Shield,
  star: Star,
  send: Send,
  filter: SlidersHorizontal,
  globe: Globe,
  camera: Camera,
  trophy: Trophy,
  flag: Flag,
  upload: Upload,
  edit: Pencil,
  download: Download,
  grid: LayoutGrid,
  trash: Trash2,
  layers: Layers,
  thumb: ThumbsUp,
  sun: Sun,
  moon: Moon,
  'mountain-snow': MountainSnow,
  expand: Maximize2,
};

export type IconName = keyof typeof MAP;

interface Props {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 22, className, strokeWidth = 1.6 }: Props) {
  const Cmp = MAP[name] ?? MapPin;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
